version: "3.7"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=cyan_development
      - MYSQL_PASSWORD=cyan
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER=cyan
    ports:
      - 3306:3306
    volumes:
      - mysql80:/var/lib/mysql

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    volumes:
      - redis60:/data

volumes:
  mysql80:
  redis60:
